# SPDX-License-Identifier: Apache-2.0
"""HTML report: score, per-block breakdown, top-5 improvements."""
from __future__ import annotations
from valiq.models import Assessment
from typing import Optional

try:
    from valiq.models import Valuation
except ImportError:
    Valuation = None  # type: ignore

_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>ValIQ Report — {project_name}</title>
<style>
body{{font-family:system-ui,sans-serif;max-width:900px;margin:0 auto;padding:2rem;color:#1a1a2e}}
h1{{color:#0057b8}}
.score-big{{font-size:4rem;font-weight:700;color:{score_color}}}
.block-row{{display:flex;align-items:center;gap:1rem;margin:.5rem 0}}
.block-name{{width:220px;font-size:.95rem}}
.bar-bg{{flex:1;background:#e2e8f0;border-radius:4px;height:14px}}
.bar-fill{{height:14px;border-radius:4px;background:{bar_color}}}
.block-pts{{width:60px;text-align:right;font-weight:600;font-size:.9rem}}
.val-box{{background:#f0fdf4;border:1px solid #86efac;border-radius:8px;padding:1rem 1.5rem;margin:1.5rem 0}}
.ati-warn{{background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:1rem 1.5rem;margin:1.5rem 0;color:#9a3412}}
table{{width:100%;border-collapse:collapse;font-size:.88rem}}
th{{background:#0057b8;color:#fff;padding:.5rem .75rem;text-align:left}}
td{{padding:.4rem .75rem;border-bottom:1px solid #e2e8f0}}
tr:nth-child(even){{background:#f8fafc}}
.improve{{background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:1rem 1.5rem;margin:1.5rem 0}}
footer{{color:#94a3b8;font-size:.8rem;margin-top:3rem;border-top:1px solid #e2e8f0;padding-top:1rem}}
</style>
</head>
<body>
<h1>ValIQ — ITAI Score Report</h1>
<p>Project: <strong>{project_name}</strong></p>
<div class="score-big">{total_score:.0f}<span style="font-size:1.5rem;color:#64748b">/1000</span></div>
{ati_block}
{valuation_block}
<h2>Block Breakdown</h2>
{blocks_html}
<h2>Top-5 Improvement Opportunities</h2>
<div class="improve">{improvements_html}</div>
<h2>All Metrics</h2>
{metrics_table}
<footer>Generated by ValIQ v0.1.0 · Apache-2.0 · <a href="https://bizdnai.com/valiq/">bizdnai.com/valiq/</a></footer>
</body>
</html>"""


def _score_color(score: float, max_score: float = 1000.0) -> str:
    pct = score / max_score
    if pct >= 0.75: return "#16a34a"
    if pct >= 0.5: return "#ca8a04"
    return "#dc2626"


def _block_bar(block, bar_color: str) -> str:
    pct = block.block_score / block.weight * 100 if block.weight else 0
    return (
        f'<div class="block-row">'
        f'<span class="block-name">{block.code}: {block.name}</span>'
        f'<div class="bar-bg"><div class="bar-fill" style="width:{pct:.0f}%;background:{bar_color}"></div></div>'
        f'<span class="block-pts">{block.block_score:.1f}/{block.weight}</span>'
        f'</div>'
    )


def to_html(assessment: Assessment, valuation=None) -> str:
    sc = assessment.total_score
    sc_color = _score_color(sc)
    bar_color = _score_color(sc)

    # ATI block
    if assessment.ati_status == "ati_required":
        ati_block = (
            '<div class="ati-warn"><strong>ATI Score Required</strong> — '
            'Valuation is blocked until you obtain your AI Trust Index score at '
            '<a href="https://bizdnai.com/index/">bizdnai.com/index/</a>. '
            'Block 6 (Compliance, 100 pts) cannot be scored without ATI.</div>'
        )
    else:
        ati_val = f"{assessment.ati_score:.1f}/10" if assessment.ati_score is not None else "N/A"
        ati_block = f'<p>AI Trust Index (ATI): <strong>{ati_val}</strong></p>'

    # Valuation block
    if valuation:
        valuation_block = (
            f'<div class="val-box">'
            f'<strong>Estimated Market Value: {valuation.display}</strong><br>'
            f'ARR: ${valuation.arr_usd:,.0f} &nbsp;·&nbsp; '
            f'Base multiple: {valuation.base_multiple}x &nbsp;·&nbsp; '
            f'ITAI multiplier: {valuation.itai_multiplier}x &nbsp;·&nbsp; '
            f'Stage: {valuation.stage} ({valuation.stage_multiplier}x)'
            f'</div>'
        )
    elif assessment.ati_status == "ati_required":
        valuation_block = '<div class="ati-warn">Valuation blocked — ATI score required.</div>'
    else:
        valuation_block = ""

    # Blocks
    blocks_html = "".join(_block_bar(b, bar_color) for b in assessment.blocks)

    # Improvements: find top-5 lowest-scoring metrics by potential gain
    all_metrics = [m for b in assessment.blocks for m in b.metrics]
    potential = [(m, (10.0 - m.score) * m.weight / 10.0) for m in all_metrics]
    potential.sort(key=lambda x: -x[1])
    top5 = potential[:5]
    improvements_html = "<ol>" + "".join(
        f"<li><strong>{m.id}</strong> ({m.name}): score {m.score:.1f}/10 — "
        f"improving to 10 would add <strong>+{gain:.1f} pts</strong> — {m.rationale}</li>"
        for m, gain in top5
    ) + "</ol>"

    # Metrics table
    rows = "".join(
        f"<tr><td>{m.block}</td><td>{m.name}</td><td>{m.weight}</td>"
        f"<td>{m.score:.1f}</td><td>{m.source}</td><td>{m.rationale}</td></tr>"
        for b in assessment.blocks for m in b.metrics
    )
    metrics_table = (
        "<table><tr><th>Block</th><th>Metric</th><th>Weight</th>"
        "<th>Score/10</th><th>Source</th><th>Rationale</th></tr>"
        + rows + "</table>"
    )

    return _TEMPLATE.format(
        project_name=assessment.project_name,
        total_score=sc,
        score_color=sc_color,
        bar_color=bar_color,
        ati_block=ati_block,
        valuation_block=valuation_block,
        blocks_html=blocks_html,
        improvements_html=improvements_html,
        metrics_table=metrics_table,
    )
